POST http://localhost:3000/register/
Content-Type: application/json



###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}


###
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIyMTY3NzQzfQ.FygKFNTFGXfb1O35itXbZbaZ3-iVOLTY1VJHFxSe7TU

### 
GET http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIyMTY3NzQzfQ.FygKFNTFGXfb1O35itXbZbaZ3-iVOLTY1VJHFxSe7TU




###

GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIyMTY3NzQzfQ.FygKFNTFGXfb1O35itXbZbaZ3-iVOLTY1VJHFxSe7TU


###

POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIyMTY3NzQzfQ.FygKFNTFGXfb1O35itXbZbaZ3-iVOLTY1VJHFxSe7TU

Content-Type: application/json


###
DELETE http://localhost:3000/tweets/1/

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIyMTY3NzQzfQ.FygKFNTFGXfb1O35itXbZbaZ3-iVOLTY1VJHFxSe7TU
Content-Type: application/json
