###
POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "kalyani@44",
  "password": "kallu@998",
  "name": "kalyani",
  "gender": "female"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
 "username": "kalyani@44",
 "password": "kallu@998"
}

###
GET http://localhost:3000/tweets/:tweetId/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbHlhbmlANDQiLCJpYXQiOjE2MjA4MDk4MTZ9.MIN7VMQ5ojt_h7CDHRP0kY2jvTkRB350T1VAYh6gvxI

### 
GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbHlhbmlANDQiLCJpYXQiOjE2MjA4MDk4MTZ9.MIN7VMQ5ojt_h7CDHRP0kY2jvTkRB350T1VAYh6gvxI



###

GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbHlhbmlANDQiLCJpYXQiOjE2MjA4MDk4MTZ9.MIN7VMQ5ojt_h7CDHRP0kY2jvTkRB350T1VAYh6gvxI

###

POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbHlhbmlANDQiLCJpYXQiOjE2MjA4MDk4MTZ9.MIN7VMQ5ojt_h7CDHRP0kY2jvTkRB350T1VAYh6gvxI
Content-Type: application/json


###
DELETE http://localhost:3000/tweets/:tweetId
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbHlhbmlANDQiLCJpYXQiOjE2MjA4MDk4MTZ9.MIN7VMQ5ojt_h7CDHRP0kY2jvTkRB350T1VAYh6gvxI
Content-Type: application/json